### ISSUE TITLE
Question about jumpers

### ISSUE THREAD

**Issue by jsanpe** [Beaupre-Circuit-Design/c64-composite-modulator#1]
Hi,

I just finished assembling this board and I am facing some difficulties figuring out the right locations for the jumpers. Let me explain.

For JP1 (power regulator jumper) the schematic is this:
<img width="572" alt="Screenshot 2021-12-31 at 11 44 30" src="https://user-images.githubusercontent.com/81919573/147819249-b5a59c14-85c5-4c5c-bcf2-01e72640646b.png">

which seems to imply that shorting 1-2 would make it work for the 656x version of the VIC-II. However, the PCB silkscreen seems to contradict this:
<img width="1301" alt="Screenshot 2021-12-31 at 11 43 09" src="https://user-images.githubusercontent.com/81919573/147819315-39adda32-a8e2-4945-89bd-b961705ff2aa.png">

with pins 1-2 being labeled as 856x.

The same situation seems to be happening with JP3 (power regulator). 

I may be misinterpreting the silkscreen or schematic, in any case just wanted to double check with you.

Happy new year, and thanks for sharing this RF mod replacement implementation!

**Comment by EddyBeaupre** [comment]
Hi,


Yes there are issues with the silkscreen on revision 20210531-2143 (it's reversed), and Q1/Q2 have the wrong pinout (BC847 is BEC, not CBE). It's been corrected in revision 20220130-1040. I am really sorry for this. I've just ordered a new batch to test, if you still want to make this modulator you may wish to wait until i've received the new prototypes and confirm that everything work.

Revision 20210531-2143 can be fix if you cut the traces for Q1/Q2 and rework them with the correct pinout with mod-wires. That's what i did to confirm that i had no other errors....

**Comment by EddyBeaupre** [comment]
Got the new PCB and finally had time to assemble everything. I can confirm that the latest revision fix all the issues. Both C64/C64C versions have been tested. Sorry for all the errors in the previous revision.
